#!/bin/sh
addgroup -g $PGID dockeruser
adduser -D -u $PUID -G dockeruser -h /home/dockeruser dockeruser
chown $PUID:$PGID /home/dockeruser
chown $PUID:$PGID `which youtube-dl`
chmod u+s,g+s `which youtube-dl`
chown root:root /root/.netrc
echo "$@"
youtube-dl $@
chmod a+x,a-r /init
