name: Linting

on:
  pull_request:
    branches: 
      - master
      - main

jobs:

  shellcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull koalaman/shellcheck:stable Image
      run: docker pull koalaman/shellcheck:stable
    - name: Run Shellcheck against shell scripts
      run: docker run --rm -i -v "$PWD:/mnt" koalaman/shellcheck:stable $(find . -type f -exec grep -m1 -l -E '^#!.*sh.*' {} \; | grep -v '/.git/')
#        docker run --rm -i -v "$PWD:/mnt" koalaman/shellcheck:stable $(find . -type f -exec grep -m1 -l -E '^#!.*execline.*' {} \; | grep -v '/.git/')

  hadolint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull hadolint/hadolint:latest Image
      run: docker pull hadolint/hadolint:latest
    - name: Run hadolint against Dockerfiles
      run: docker run --rm -i -v "$PWD":/workdir --workdir /workdir --entrypoint hadolint hadolint/hadolint --ignore DL3008 --ignore SC2068 --ignore DL3003 --ignore DL3013 $(find . -type f -iname "Dockerfile*")

  markdownlint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull markdownlint/markdownlint:latest Image
      run: docker pull markdownlint/markdownlint:latest
    - name: Run markdownlint against *.md files
      run: docker run --rm -i -v "$(pwd)":/workdir --workdir /workdir markdownlint/markdownlint:latest --rules ~MD007,~MD013,~MD033 $(find . -type f -iname '*.md' | grep -v '/.git/')
      